# Site settings
title: Scubed Software
email: hubert@scubedsoft.com
description: > # this means to ignore newlines until "baseurl:"
  Software Craftsmanship Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.scubedsoft.com" # the base hostname & protocol for your site
twitter_username: hubert.k.lee
github_username:  hube

# Build settings
markdown: kramdown
